### ISSUE TITLE
Integrate with in-game playback

### ISSUE THREAD

**Issue by mlugg** [RainbowwPhoenixx/p2tas-lang#4]
Using a TCP or UNIX socket exposed by SAR, the plugin could communicate with the TAS player and integrate nicely into TAS playback in the following ways:
- A button in VS code could trigger SAR to play the TAS
- While the TAS is playing, the current framebulk could be highlighted in VS code, so you can see what is being run when
- You could have basic playback controls in VS code, e.g. a slider for playback rate
- You could set breakpoints in VS code to make SAR skip to that tick. This will be much more useful if we manage to figure out frame advancing

**Comment by RainbowwPhoenixx** [comment]
Link to outlined protocol : https://cdn.discordapp.com/attachments/735150585174687856/912168703326576661/tas_proto

I had a good idea to extend this protocol, the extension could request the parsing of a TAS file, (without playing the TAS) in order to outline problems in the syntax in the script directly into VS Code. Ideally we'd implement a full fledged language server, but I consider that to be too high effort considering the size of the files we are dealing with.

**Comment by mlugg** [comment]
Personally I don't think that should be handled by the SAR integration; parsing is work that shouldn't depend on the game in any way, and can just be replicated directly in the extension instead.

**Comment by mlugg** [comment]
3f305b8
